### ISSUE TITLE
MemoryError: std::bad_alloc When Using Rannc Built From Source

### ISSUE THREAD

**Issue by sslfuhan** [nict-wisdom/rannc#10]
I did the installation of pyrannc v0.7.3  from the source according to the [building from source page](https://nict-wisdom.github.io/rannc/build.html) in the documentation. The installation was succeeded but when I tried to just import pyrannc the memory error occurred.
Here is the output:
> File "/home/ai/install/miniconda3/envs/rannc/lib/python3.9/site-packages/pyrannc-0.7.3-py3.9-linux-x86_64.egg/pyrannc/__init__.py", line 32, in <module>
> rannc = _pyrannc.get_rannc()
> MemoryError: std::bad_alloc

I use 4 nvidia Tesla p100 and the following software:
- CUDA version 11.3
- cuDNN: v8.4.1
- NCCL version 2.11.4
- Python 3.9.13
- MPI version openmpi-4.0
- pybind11 v2.8.1

I guess it's something wrong with cudaMalloc or other, could you help me figure it out?

**Comment by tohtana** [comment]
Thank you for your report.
I couldn't reproduce the error, but the error indicates a failure of *host* memory allocation, not CUDA device memory allocation.

The function `` _pyrannc.get_rannc()`` only creates an instance of  ``RaNNCFactory`` and allocates a very small amount of memory. It is unlikely that the function causes an out-of-memory error.
https://github.com/nict-wisdom/rannc/blob/main/src/bind/RaNNCFactory.cpp#L14

If you could compile the code, can you add some memory allocation around the above line and see what happens?

You can also try our [binary distribution packages](https://nict-wisdom.github.io/rannc/installation.html).

**Comment by nict-wisdom** [comment]
Thank you for your report.
I couldn't reproduce the error, but the error indicates a failure of *host* memory allocation, not CUDA device memory allocation.

The function `` _pyrannc.get_rannc()`` only creates an instance of  ``RaNNCFactory`` and allocates a very small amount of memory. It is unlikely that the function causes an out-of-memory error.
https://github.com/nict-wisdom/rannc/blob/main/src/bind/RaNNCFactory.cpp#L14

If you could compile the code, can you add some memory allocation around the above line and see what happens?

You can also try our [binary distribution packages](https://nict-wisdom.github.io/rannc/installation.html).

**Comment by sslfuhan** [comment]
Thank you for your reply.
I located the error at [src/config.cpp](https://github.com/nict-wisdom/rannc/blob/main/src/Config.cpp) from line 220 to line 222. It is likely that the"/" operator did not work, the variable "conf_dir" did not append "Default_conf_dir_name" as "/home/.pyrannc" but just "/home". 
Here is my "conf_dir" and "conf_file" following:
conf_dir: "/home/ai"  
conf_file: "/home/ai"
So the toml library read the file size as (2^63-1) , which was unable to load into memory. I have never used Boost filesystem libraries before, so i don't know how to fix this. Could you please share me the version of Boost library you used in your work?

**Comment by nict-wisdom** [comment]
Thank you for identifying the problem!

We are currently using Boost v1.78.0.
You can see versions of modules and libraries in [Dockerfile](https://github.com/nict-wisdom/rannc/blob/16114f3834ced71677e2a1b8d80a5fbb74f89757/docker/ubuntu/base/Dockerfile).

Thanks to your investigation, I could improve the error handling while loading the config file in 16114f3834ced71677e2a1b8d80a5fbb74f89757.
I hope the change will help users solve similar problems.

**Comment by sslfuhan** [comment]
Thank you!
My problem was solved!
