### ISSUE TITLE
I want to watch the result of graph partition. But I can't open the file `graph_profile_.bin`

### ISSUE THREAD

**Issue by DY-TL** [nict-wisdom/rannc#5]
I got full of Garbled code when I try to open the file `graph_profile_.bin`. Could you tell me how to open this file?

**Comment by nict-wisdom** [comment]
Thank you for your question.

I added a [FAQ](https://nict-wisdom.github.io/rannc/faq.html#how-can-i-check-partitioning-results) that explains how to display partitioning results.
I think #3 will also help.

**Comment by DY-TL** [comment]
Thank you for your direction.

**Comment by DY-TL** [comment]
Thank you for your direction.
